In [1]:
import numpy as np

In [34]:
arr1=np.random.randint(0,10,5)
arr1

array([1, 7, 8, 2, 4])

In [21]:
arr2=np.linspace(0,20,5)
arr2

array([ 0.,  5., 10., 15., 20.])

In [13]:
arr1+arr2

array([ 3., 11., 20., 23., 27., 38.])

In [14]:
arr1*arr2

array([  0.,  30.,  96.,  90.,  72., 240.])

In [16]:
arr2/arr1

array([0.  , 1.2 , 1.5 , 3.6 , 8.  , 3.75])

In [33]:
arr3=np.array([[1,3,1,3,0],[3,2,1,0,2],[11,10,6,7,9]])
arr3

array([[ 1,  3,  1,  3,  0],
       [ 3,  2,  1,  0,  2],
       [11, 10,  6,  7,  9]])

In [35]:
arr4=np.random.randint(0,10,size=(3,5))
arr4

array([[7, 8, 4, 3, 2],
       [1, 2, 8, 5, 1],
       [7, 0, 7, 0, 4]])

In [38]:
arr3.max(axis=0)

array([11, 10,  6,  7,  9])

In [43]:
arr3.max(axis=1)

array([ 3,  3, 11])

In [44]:
arr4.reshape(5,3)

array([[7, 8, 4],
       [3, 2, 1],
       [2, 8, 5],
       [1, 7, 0],
       [7, 0, 4]])